// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

// Try local .env first, then fall back to monorepo root .env
const localEnv = resolve(__dirname, ".env");
const rootEnv = resolve(__dirname, "../../.env");
loadEnv({ path: existsSync(localEnv) ? localEnv : rootEnv });

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set (looked in apps/api/.env and ./.env)");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
